remote_theme: thelehhman/texture
title: Corona Outbreak Analysis
description: Coronavirus Outbreak Analysis. Logistic pandemic modeling. Kristian Schwienbacher

texture:
  title: Corona Outbreak Analysis
  tagline: Kristian Schwienbacher
  style: blue
  analytics_id: 'UA-161409017-1'

  social_links:
    twitter: kr3dde
    github:  kredde